version: "3.8"

services:
  mongodb:
    image: mongodb-with-shell
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth --bind_ip 0.0.0.0
    restart: always

volumes:
  mongodb_data:
